### ISSUE TITLE
1.16.5 crash + other issues

### ISSUE THREAD

**Issue by ThatTonybo** [ldtteam/PerViamInvenire#10]
Since adding the mod, I've noticed that mobs are now:
- Spinning at random, and not moving until punched (though they start spinning again)
- Fail to jump, especially in the case of hostile mobs
- Won't fall when they used to, such as zombies above you falling down (they seem to stay up and won't jump down)

Additionally, I've faced two game crashes with the mod seeming to be the cause (most of the report cut out due to length):
```
Time: 6/12/21 5:57 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51] {}
	at com.ldtteam.perviaminvenire.pathfinding.PerViamInvenireGroundPathNavigator.func_75508_h(PerViamInvenireGroundPathNavigator.java:667) ~[?:1.16.5-0.0.23-ALPHA] {re:classloading}
	at com.ldtteam.perviaminvenire.pathfinding.PerViamInvenireGroundPathNavigator.func_75501_e(PerViamInvenireGroundPathNavigator.java:264) ~[?:1.16.5-0.0.23-ALPHA] {re:classloading}
	at com.ldtteam.perviaminvenire.pathfinding.PerViamInvenireClimberPathNavigator.func_75501_e(PerViamInvenireClimberPathNavigator.java:70) ~[?:1.16.5-0.0.23-ALPHA] {re:classloading}
```

Full crash reports:
[crash-2021-06-12_17.57.46-server.txt](https://github.com/ldtteam/PerViamInvenire/files/6641875/crash-2021-06-12_17.57.46-server.txt)
[crash-2021-06-11_11.16.46-server.txt](https://github.com/ldtteam/PerViamInvenire/files/6641876/crash-2021-06-11_11.16.46-server.txt)

Here's the mods in the pack:
![image](https://user-images.githubusercontent.com/28176227/121769838-3a1fb480-cba9-11eb-84f4-da3cb5ef3b46.png)

Forge version 36.1.0, Minecraft version 1.16.5

**Comment by marchermans** [comment]
The crashes where fixed in the latest update.
Could you create new issues which exactly describe the pathfinding issues you are seeing?

Preferrably with some recordings of the cases.
